reddit:
  client_id: "sIzwVhgwRwCGQ39qYOgSnA"
  client_secret: "ki4WFaeD93RYOmyEnoW4hf4Dx8miKg"
  user_agent: "script:SentimentAnalysis:v1.0 (by /u/your_username)"

subreddits:
  - "wallstreetbets"
  - "stocks"
  - "investing"

data_collection:
  post_limit: 100
  time_filter: "day" 